<a href="https://colab.research.google.com/github/KARINAgoncalvesSOARES/numpy/blob/main/numpy_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 <h2 align="center"> Numpy

Data Scientist Jr.: Karina Gonçalves Soares

Link de estudo:

* [Bibliotecas para manipulação de dados](https://learn-us-east-1-prod-fleet02-xythos.content.blackboardcdn.com/5d152e0e8981d/17844897?X-Blackboard-S3-Bucket=learn-us-east-1-prod-fleet01-xythos&X-Blackboard-Expiration=1676505600000&X-Blackboard-Signature=lkHWJZohlEWpQ4r9xwnIjUZ3RGxIGMMciiSVvk%2Baohk%3D&X-Blackboard-Client-Id=152625&X-Blackboard-S3-Region=us-east-1&response-cache-control=private%2C%20max-age%3D21600&response-content-disposition=inline%3B%20filename%2A%3DUTF-8%27%27teorico.pdf&response-content-type=application%2Fpdf&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEJv%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMSJIMEYCIQCz%2BSTP0jHEwfxCWjOwiV1PgTzx7LZjL0Z5HWaEW8KEXQIhAPS%2Fau4SSdNNAv5HOuSIdsBwpqYR9zyJsbQoPrUqRUyeKs0ECDQQAhoMNjM1NTY3OTI0MTgzIgyBdytIECm3AKRatKIqqgTzix%2BevMIqCDspb%2BhXZTepfVS2xhAzm1%2FOfzI5LCpbftphP6tbTyGdlsi1InvwBWZpxPKkWyeDxL2QBZAbQ6mCj6fkeYEO4cQ5VSsdoXkSRZo6vuF3mZMrfENOAesTzPNGPif0eL0SmhPxVbjhW3KsR%2B7giCyXQslop0BUWArhlg6LP6lN%2BgoHXJtyGxD8ZAOMO68EAmxkq%2Fv3ccfrhHvsMb0T%2BKPPG82xEfcHMkRysUezj84pwJNF3jncEqkZG4aQMgywwx5qmEgaVaSi3CqYZ9FTpy0iZPJX4CaTJd5gcPJQHgvsnhOPnWpY4OfwO53B7hjom9gdsyJhwLgydgKdqm6rKOaUlnDuoyzyz%2BP4%2Bb3eUobA28k8ca412WEVAehBI2ThqudBReXJDEijQkaUx%2F%2BLawtPSNYsytAx9gow997HVvMTDA4%2FXkXXiynNh8ItpONH8FYUYeRdROl6cZUCAf9jikzGjio3OYcZ4IaZBOUV%2FzaENK4Qhh3TV9VGpk0HjQ5sa%2FRICNNTQdRqva8yAa%2FW1jmOpjERXEgzC%2BBLOOLP5CcXbxIhaFwLuAbzw4%2FWh8N91wRdfdmRGJjzFyang19yBkrIOMxjTMxhg8XScCaiylIwNO2jSxNg7DwttsFS5kqLeSZKXnzS2EaYzyBKj3LA46aYLMxP5vJjcuQbzxicy1o9beELRnZuUNiS1HsqlhQvNoqoTUIGPcoCGJjXamoMEui18QY%2FQDD90rSfBjqoAfvZtBSbpkDVbPq%2BYzcufEilTBDv231baoDQ%2BozCO00asGfef9t1FnayCeJTUYkCrcF%2FieTxnRKNLH6Vp7eY2upnDhUfcBY54ZGoiiOR41U6ZeHR%2BxPAB11HkSKfgyclg2wJrCK9E5Oxgd63v3SV%2FYjfn3yZzLnYTBZU1JZHc0DkuZoUgNxk8JaIpXgPEzJGxc1F34E0KEpPz0cWLUOAkLyjRnBN30bmrQ%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20230215T180000Z&X-Amz-SignedHeaders=host&X-Amz-Expires=21600&X-Amz-Credential=ASIAZH6WM4PL3WFKSPVS%2F20230215%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=c2e29328a6cdff83162514e353a47d7bc0ca38509d88decd0b5d1aa0950969b8)

#Numpy

Primeiro, é importante lembrar que você precisa importar essa biblioteca no seu código. Convencionou-se que a bibliteca deve ser importada da seguite maneira:



In [1]:
import numpy as np

Agora, vejamos um primeiro exemplo de criação de um array Numpy:

In [2]:
a = np.array([0,1,2,3])
print(a)
print(type(a))
print(a.ndim)

[0 1 2 3]
<class 'numpy.ndarray'>
1


###Criação de Arrays
####Construção Manual de Arrays


In [3]:
b = np.array([[0,1,2],
              [3,4,5]])

print(b)
print('\n')
print(b.ndim)
print('\n')
print(b.shape)
print('\n')
print(len(b))
print('\n')
print(b.cumsum()) # Realiza a soma dos elementos do vetor

[[0 1 2]
 [3 4 5]]


2


(2, 3)


2


[ 0  1  3  6 10 15]


####Criação utilizando funções

In [4]:
c = np.arange(10, 20)

print(c)
print('')

#np.linspace() -> Permite criar um array uniformemente espaçados seguindo os elementos passados como parametro.
d = np.linspace(1,10,13, endpoint=False) 
print(d)

[10 11 12 13 14 15 16 17 18 19]

[1.         1.69230769 2.38461538 3.07692308 3.76923077 4.46153846
 5.15384615 5.84615385 6.53846154 7.23076923 7.92307692 8.61538462
 9.30769231]


### Arrays comuns

In [5]:
#um = np.ones(3)
um = np.ones((2,3))
print(um)
print('')

#e = np.zeros(5)
e = np.zeros((5,5))
print(e)
print('')

f = np.random.rand(10,10) #Criando um array de números aleatórios
print(f)

[[1. 1. 1.]
 [1. 1. 1.]]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[0.72513817 0.51183688 0.8362009  0.71028523 0.32070029 0.34564127
  0.34019747 0.01092671 0.2796223  0.28485484]
 [0.77759117 0.65036436 0.34156651 0.77445648 0.5134916  0.96509642
  0.05431114 0.13630911 0.82132383 0.07736417]
 [0.4893226  0.29889574 0.36768148 0.19622433 0.99636443 0.41685833
  0.75320779 0.64432281 0.25831253 0.32884887]
 [0.17089752 0.70670515 0.728624   0.29467307 0.82899687 0.17904577
  0.7552268  0.37923362 0.21444507 0.28172129]
 [0.13243358 0.15933483 0.30265415 0.60944737 0.09235555 0.99671085
  0.84882818 0.0668882  0.24756146 0.45231479]
 [0.46224033 0.36146645 0.81163195 0.69621088 0.71613575 0.6162447
  0.92349978 0.91746447 0.84563094 0.09571815]
 [0.52798452 0.27325909 0.75401826 0.22002691 0.95815138 0.76666205
  0.56999239 0.60918336 0.82597696 0.23637564]
 [0.71286435 0.74672725 0.58042745 0.30887868 0.64592966 0.68354178
  0.520179

In [6]:
# Criando array diagonal
g = np.eye(3)
print(g)
print('')

h = np.diag(np.array([1,2,3,4]))
print(h)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


###Indexação e Cortes (Slices) de Arrays

In [7]:
a = np.arange(10,21)
print(a)
print(a[-2]) # Acessando elementos da array
print('')

print(a[2:9])
print('')
print(a[8:2:-1])

[10 11 12 13 14 15 16 17 18 19 20]
19

[12 13 14 15 16 17 18]

[18 17 16 15 14 13]


In [14]:
b = np.random.rand(5,5)
print(b)
print('')
print(b[0][1]) # Culuna x linha
print('')

b[0,1] = 10 # Mudando o valor da array passando a posição como parâmetro
print(b)
print('')

# Slice
print(b[0:2, 2]) # Aqui está sendo específicado as linhas(0 e 2) e a coluna(2)
print(' ')
print(b.size) # Saber quantidade de elementos

[[0.45468445 0.16554458 0.53467639 0.90951658 0.16913507]
 [0.95192042 0.70228316 0.00387547 0.440458   0.36342387]
 [0.26876564 0.28601288 0.7220848  0.78352954 0.6905439 ]
 [0.32338428 0.37498584 0.35518261 0.18431131 0.08171051]
 [0.31809868 0.66972467 0.89506535 0.74346151 0.74336521]]

0.16554458383454784

[[4.54684448e-01 1.00000000e+01 5.34676391e-01 9.09516577e-01
  1.69135068e-01]
 [9.51920418e-01 7.02283155e-01 3.87546996e-03 4.40457997e-01
  3.63423865e-01]
 [2.68765639e-01 2.86012881e-01 7.22084805e-01 7.83529540e-01
  6.90543902e-01]
 [3.23384277e-01 3.74985840e-01 3.55182612e-01 1.84311306e-01
  8.17105145e-02]
 [3.18098678e-01 6.69724667e-01 8.95065348e-01 7.43461512e-01
  7.43365205e-01]]

[0.53467639 0.00387547]
 
25


In [18]:
v = np.array([10, 33, 78, 100, 175])

print(np.mean(v)) # Calculando a média, aponta para onde se concentram os dados
print(' ')

print(np.std(v)) # Desvio padrão, variação existente em relação a média
print(' ')

print(np.var(v)) # Indica o quão longe os valores estão do esperado
print(' ')

print(np.sum(v)) # Somatória dos números da array
print(' ')

print(np.prod(v)) #Retona o produto(multiplicação) da matriz
print(' ')

79.2
 
57.50617358162513
 
3306.96
 
396
 
450450000
 


In [21]:
v2 = np.arange(10)

print(v2)
print('')

print(v2[1:9:2]) # Fatiamento usando [start: stop: step]
print('')

[0 1 2 3 4 5 6 7 8 9]

[1 3 5 7]



In [23]:
# Comparando vetores
v3 = np.array([2, 2, 3, 1])
v4 = np.array([4, 5, 3, 1])

print(v3==v4) # Analisa se os ítens das arrays são iguais
print(' ')

print(v3.min()) # Valor mínimo
print(v3.max()) # Valor máximo

[False False  True  True]
 
1
3


In [24]:
# Criando arrays com números repetidos a partir dos valores de outro vetor
v5 = np.repeat(v3, 3)
print(v5)
print(' ')

# Juntando dois vetores
v6 = np.concatenate((v3, v4), axis=0)
print(v6)

[2 2 2 2 2 2 3 3 3 1 1 1]
 
[2 2 3 1 4 5 3 1]
