<a href="https://colab.research.google.com/github/KARINAgoncalvesSOARES/numpy/blob/main/numpy_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 <h2 align="center"> Numpy

Data Scientist Jr.: Karina Gonçalves Soares

Link de estudo:

* [Bibliotecas para manipulação de dados](https://learn-us-east-1-prod-fleet02-xythos.content.blackboardcdn.com/5d152e0e8981d/17844897?X-Blackboard-S3-Bucket=learn-us-east-1-prod-fleet01-xythos&X-Blackboard-Expiration=1676505600000&X-Blackboard-Signature=lkHWJZohlEWpQ4r9xwnIjUZ3RGxIGMMciiSVvk%2Baohk%3D&X-Blackboard-Client-Id=152625&X-Blackboard-S3-Region=us-east-1&response-cache-control=private%2C%20max-age%3D21600&response-content-disposition=inline%3B%20filename%2A%3DUTF-8%27%27teorico.pdf&response-content-type=application%2Fpdf&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEJv%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMSJIMEYCIQCz%2BSTP0jHEwfxCWjOwiV1PgTzx7LZjL0Z5HWaEW8KEXQIhAPS%2Fau4SSdNNAv5HOuSIdsBwpqYR9zyJsbQoPrUqRUyeKs0ECDQQAhoMNjM1NTY3OTI0MTgzIgyBdytIECm3AKRatKIqqgTzix%2BevMIqCDspb%2BhXZTepfVS2xhAzm1%2FOfzI5LCpbftphP6tbTyGdlsi1InvwBWZpxPKkWyeDxL2QBZAbQ6mCj6fkeYEO4cQ5VSsdoXkSRZo6vuF3mZMrfENOAesTzPNGPif0eL0SmhPxVbjhW3KsR%2B7giCyXQslop0BUWArhlg6LP6lN%2BgoHXJtyGxD8ZAOMO68EAmxkq%2Fv3ccfrhHvsMb0T%2BKPPG82xEfcHMkRysUezj84pwJNF3jncEqkZG4aQMgywwx5qmEgaVaSi3CqYZ9FTpy0iZPJX4CaTJd5gcPJQHgvsnhOPnWpY4OfwO53B7hjom9gdsyJhwLgydgKdqm6rKOaUlnDuoyzyz%2BP4%2Bb3eUobA28k8ca412WEVAehBI2ThqudBReXJDEijQkaUx%2F%2BLawtPSNYsytAx9gow997HVvMTDA4%2FXkXXiynNh8ItpONH8FYUYeRdROl6cZUCAf9jikzGjio3OYcZ4IaZBOUV%2FzaENK4Qhh3TV9VGpk0HjQ5sa%2FRICNNTQdRqva8yAa%2FW1jmOpjERXEgzC%2BBLOOLP5CcXbxIhaFwLuAbzw4%2FWh8N91wRdfdmRGJjzFyang19yBkrIOMxjTMxhg8XScCaiylIwNO2jSxNg7DwttsFS5kqLeSZKXnzS2EaYzyBKj3LA46aYLMxP5vJjcuQbzxicy1o9beELRnZuUNiS1HsqlhQvNoqoTUIGPcoCGJjXamoMEui18QY%2FQDD90rSfBjqoAfvZtBSbpkDVbPq%2BYzcufEilTBDv231baoDQ%2BozCO00asGfef9t1FnayCeJTUYkCrcF%2FieTxnRKNLH6Vp7eY2upnDhUfcBY54ZGoiiOR41U6ZeHR%2BxPAB11HkSKfgyclg2wJrCK9E5Oxgd63v3SV%2FYjfn3yZzLnYTBZU1JZHc0DkuZoUgNxk8JaIpXgPEzJGxc1F34E0KEpPz0cWLUOAkLyjRnBN30bmrQ%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20230215T180000Z&X-Amz-SignedHeaders=host&X-Amz-Expires=21600&X-Amz-Credential=ASIAZH6WM4PL3WFKSPVS%2F20230215%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=c2e29328a6cdff83162514e353a47d7bc0ca38509d88decd0b5d1aa0950969b8)

#Numpy

Primeiro, é importante lembrar que você precisa importar essa biblioteca no seu código. Convencionou-se que a bibliteca deve ser importada da seguite maneira:



In [1]:
import numpy as np

Agora, vejamos um primeiro exemplo de criação de um array Numpy:

In [2]:
a = np.array([0,1,2,3])
print(a)
print(type(a))
print(a.ndim)

[0 1 2 3]
<class 'numpy.ndarray'>
1


###Criação de Arrays
####Construção Manual de Arrays


In [9]:
b = np.array([[0,1,2],
              [3,4,5]])

print(b)
print('\n')
print(b.ndim)
print('\n')
print(b.shape)
print('\n')
print(len(b))
print('\n')
print(b.cumsum()) # Realiza a soma dos elementos do vetor

[[0 1 2]
 [3 4 5]]


2


(2, 3)


2


[ 0  1  3  6 10 15]


####Criação utilizando funções

In [4]:
c = np.arange(10, 20)

print(c)
print('')

#np.linspace() -> Permite criar um array uniformemente espaçados seguindo os elementos passados como parametro.
d = np.linspace(1,10,13, endpoint=False) 
print(d)

[10 11 12 13 14 15 16 17 18 19]

[1.         1.69230769 2.38461538 3.07692308 3.76923077 4.46153846
 5.15384615 5.84615385 6.53846154 7.23076923 7.92307692 8.61538462
 9.30769231]


### Arrays comuns

In [5]:
#um = np.ones(3)
um = np.ones((2,3))
print(um)
print('')

#e = np.zeros(5)
e = np.zeros((5,5))
print(e)
print('')

f = np.random.rand(10,10) #Criando um array de números aleatórios
print(f)

[[1. 1. 1.]
 [1. 1. 1.]]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[0.08488604 0.4969638  0.02540344 0.66353312 0.2973429  0.52273184
  0.45507913 0.6162106  0.06084917 0.41731414]
 [0.93752864 0.27097411 0.33613676 0.80415695 0.77968336 0.32629044
  0.52090648 0.43322187 0.0024911  0.91115111]
 [0.02885512 0.25423753 0.57739268 0.62660792 0.62711619 0.83029235
  0.25736615 0.35655231 0.43764753 0.10621933]
 [0.1928586  0.1917188  0.88854242 0.46466483 0.33357989 0.78531378
  0.82612901 0.44487513 0.70281343 0.33598568]
 [0.50077874 0.94005696 0.90158393 0.70467777 0.65498568 0.06207685
  0.88529278 0.09576139 0.71396301 0.24426901]
 [0.34228006 0.99906236 0.58916087 0.91195414 0.6312913  0.86282877
  0.68874064 0.68658373 0.0545833  0.66200996]
 [0.58125558 0.31651875 0.10711692 0.01659082 0.29249294 0.36817125
  0.51624686 0.11731764 0.95747079 0.98882097]
 [0.57045045 0.58598609 0.99850915 0.70163037 0.58250042 0.99084318
  0.88463

In [6]:
# Criando array diagonal
g = np.eye(3)
print(g)
print('')

h = np.diag(np.array([1,2,3,4]))
print(h)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


###Indexação e Cortes (Slices) de Arrays

In [7]:
a = np.arange(10,21)
print(a)
print(a[-2]) # Acessando elementos da array
print('')

print(a[2:9])
print('')
print(a[8:2:-1])

[10 11 12 13 14 15 16 17 18 19 20]
19

[12 13 14 15 16 17 18]

[18 17 16 15 14 13]


In [8]:
b = np.random.rand(5,5)
print(b)
print('')
print(b[0][1]) # Culuna x linha
print('')

b[0,1] = 10 # Mudando o valor da array passando a posição como parâmetro
print(b)
print('')

# Slice
print(b[0:2, 2]) # Aqui está sendo específicado as linhas(0 e 2) e a coluna(2)

[[0.2785958  0.25834512 0.63345069 0.7998533  0.27352259]
 [0.25296625 0.02880004 0.74721339 0.51423574 0.0241847 ]
 [0.12108713 0.67706417 0.20341286 0.89764597 0.46214994]
 [0.44899619 0.5014657  0.25932439 0.98479003 0.27636844]
 [0.87906558 0.84736175 0.65418721 0.76578224 0.46585339]]

0.25834511820927164

[[ 0.2785958  10.          0.63345069  0.7998533   0.27352259]
 [ 0.25296625  0.02880004  0.74721339  0.51423574  0.0241847 ]
 [ 0.12108713  0.67706417  0.20341286  0.89764597  0.46214994]
 [ 0.44899619  0.5014657   0.25932439  0.98479003  0.27636844]
 [ 0.87906558  0.84736175  0.65418721  0.76578224  0.46585339]]

[0.63345069 0.74721339]
