<a href="https://colab.research.google.com/github/KARINAgoncalvesSOARES/numpy/blob/main/numpy_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 <h1 align="center"> Numpy</h1>

Data Scientist Jr.: Karina Gonçalves Soares

Link de estudo:

* [Bibliotecas para manipulação de dados](https://learn-us-east-1-prod-fleet02-xythos.content.blackboardcdn.com/5d152e0e8981d/17844897?X-Blackboard-S3-Bucket=learn-us-east-1-prod-fleet01-xythos&X-Blackboard-Expiration=1676505600000&X-Blackboard-Signature=lkHWJZohlEWpQ4r9xwnIjUZ3RGxIGMMciiSVvk%2Baohk%3D&X-Blackboard-Client-Id=152625&X-Blackboard-S3-Region=us-east-1&response-cache-control=private%2C%20max-age%3D21600&response-content-disposition=inline%3B%20filename%2A%3DUTF-8%27%27teorico.pdf&response-content-type=application%2Fpdf&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEJv%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMSJIMEYCIQCz%2BSTP0jHEwfxCWjOwiV1PgTzx7LZjL0Z5HWaEW8KEXQIhAPS%2Fau4SSdNNAv5HOuSIdsBwpqYR9zyJsbQoPrUqRUyeKs0ECDQQAhoMNjM1NTY3OTI0MTgzIgyBdytIECm3AKRatKIqqgTzix%2BevMIqCDspb%2BhXZTepfVS2xhAzm1%2FOfzI5LCpbftphP6tbTyGdlsi1InvwBWZpxPKkWyeDxL2QBZAbQ6mCj6fkeYEO4cQ5VSsdoXkSRZo6vuF3mZMrfENOAesTzPNGPif0eL0SmhPxVbjhW3KsR%2B7giCyXQslop0BUWArhlg6LP6lN%2BgoHXJtyGxD8ZAOMO68EAmxkq%2Fv3ccfrhHvsMb0T%2BKPPG82xEfcHMkRysUezj84pwJNF3jncEqkZG4aQMgywwx5qmEgaVaSi3CqYZ9FTpy0iZPJX4CaTJd5gcPJQHgvsnhOPnWpY4OfwO53B7hjom9gdsyJhwLgydgKdqm6rKOaUlnDuoyzyz%2BP4%2Bb3eUobA28k8ca412WEVAehBI2ThqudBReXJDEijQkaUx%2F%2BLawtPSNYsytAx9gow997HVvMTDA4%2FXkXXiynNh8ItpONH8FYUYeRdROl6cZUCAf9jikzGjio3OYcZ4IaZBOUV%2FzaENK4Qhh3TV9VGpk0HjQ5sa%2FRICNNTQdRqva8yAa%2FW1jmOpjERXEgzC%2BBLOOLP5CcXbxIhaFwLuAbzw4%2FWh8N91wRdfdmRGJjzFyang19yBkrIOMxjTMxhg8XScCaiylIwNO2jSxNg7DwttsFS5kqLeSZKXnzS2EaYzyBKj3LA46aYLMxP5vJjcuQbzxicy1o9beELRnZuUNiS1HsqlhQvNoqoTUIGPcoCGJjXamoMEui18QY%2FQDD90rSfBjqoAfvZtBSbpkDVbPq%2BYzcufEilTBDv231baoDQ%2BozCO00asGfef9t1FnayCeJTUYkCrcF%2FieTxnRKNLH6Vp7eY2upnDhUfcBY54ZGoiiOR41U6ZeHR%2BxPAB11HkSKfgyclg2wJrCK9E5Oxgd63v3SV%2FYjfn3yZzLnYTBZU1JZHc0DkuZoUgNxk8JaIpXgPEzJGxc1F34E0KEpPz0cWLUOAkLyjRnBN30bmrQ%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20230215T180000Z&X-Amz-SignedHeaders=host&X-Amz-Expires=21600&X-Amz-Credential=ASIAZH6WM4PL3WFKSPVS%2F20230215%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=c2e29328a6cdff83162514e353a47d7bc0ca38509d88decd0b5d1aa0950969b8)

#Numpy

Primeiro, é importante lembrar que você precisa importar essa biblioteca no seu código. Convencionou-se que a bibliteca deve ser importada da seguite maneira:



In [1]:
import numpy as np

Agora, vejamos um primeiro exemplo de criação de um array Numpy:

In [2]:
a = np.array([0,1,2,3])
print(a)
print(type(a))
print(a.ndim)

[0 1 2 3]
<class 'numpy.ndarray'>
1


### Criação de Arrays
#### Construção Manual de Arrays


In [3]:
b = np.array([[0,1,2],
              [3,4,5]])

print(b)
print('\n')
print(b.ndim)
print('\n')
print(b.shape)
print('\n')
print(len(b))
print('\n')
print(b.cumsum()) # Realiza a soma dos elementos do vetor

[[0 1 2]
 [3 4 5]]


2


(2, 3)


2


[ 0  1  3  6 10 15]


### Arrays comuns

In [4]:
#um = np.ones(3)
um = np.ones((2,3))
print(um)
print('')

#e = np.zeros(5)
e = np.zeros((5,5))
print(e)
print('')

f = np.random.rand(10,10) #Criando um array de números aleatórios
print(f)

[[1. 1. 1.]
 [1. 1. 1.]]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[0.82685369 0.2864735  0.74417114 0.58210985 0.6736406  0.19973049
  0.44321318 0.04122918 0.6577303  0.90400498]
 [0.88061103 0.5066877  0.65657986 0.09645941 0.61206563 0.50262758
  0.35559141 0.23688279 0.11067095 0.2383351 ]
 [0.44736489 0.47279496 0.23747169 0.9493865  0.51605582 0.29357324
  0.88476564 0.99942177 0.65955071 0.5268136 ]
 [0.81232655 0.01160764 0.10337386 0.48513999 0.84876365 0.12058096
  0.03912547 0.1233324  0.0843059  0.34947539]
 [0.58037791 0.73891619 0.28472912 0.27464195 0.87058954 0.64612887
  0.56427044 0.50018772 0.85006957 0.47404604]
 [0.29447006 0.61244162 0.58676163 0.4887431  0.30002303 0.36322293
  0.18782168 0.17001685 0.38167564 0.64022822]
 [0.88901506 0.54051425 0.64243935 0.12771399 0.93504651 0.42451307
  0.84448295 0.68921852 0.50866665 0.35955283]
 [0.17417295 0.76245033 0.06031417 0.93173004 0.47197412 0.61909987
  0.44649

In [5]:
# Criando array diagonal
g = np.eye(3)
print(g)
print('')

h = np.diag(np.array([1,2,3,4]))
print(h)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


### Indexação e Cortes (Slices) de Arrays

In [6]:
a = np.arange(10,21)
print(a)
print(a[-2]) # Acessando elementos da array
print('')

print(a[2:9])
print('')
print(a[8:2:-1])

[10 11 12 13 14 15 16 17 18 19 20]
19

[12 13 14 15 16 17 18]

[18 17 16 15 14 13]


In [7]:
b = np.random.rand(5,5)
print(b)
print('')
print(b[0][1]) # Linha Vs Coluna
print('')

b[0,1] = 10 # Mudando o valor da array passando a posição como parâmetro
print(b)
print('')

# Slice
print(b[0:2, 2]) # Estamos imprimindo as linhas 0 e 1 (indexação exclusiva 0 e 2) da coluna 3 (indexação 2)
print(' ')
print(b.size) # Saber quantidade de elementos

[[0.61280583 0.59576147 0.25534139 0.94168503 0.65723123]
 [0.34821333 0.46520351 0.57897903 0.51586628 0.69500156]
 [0.79222607 0.26482588 0.10248392 0.31032092 0.79314049]
 [0.49681189 0.71541764 0.0893809  0.06850463 0.17460987]
 [0.6874348  0.76075351 0.74129897 0.52158964 0.34772744]]

0.5957614716798536

[[ 0.61280583 10.          0.25534139  0.94168503  0.65723123]
 [ 0.34821333  0.46520351  0.57897903  0.51586628  0.69500156]
 [ 0.79222607  0.26482588  0.10248392  0.31032092  0.79314049]
 [ 0.49681189  0.71541764  0.0893809   0.06850463  0.17460987]
 [ 0.6874348   0.76075351  0.74129897  0.52158964  0.34772744]]

[0.25534139 0.57897903]
 
25


#### Funções NumPy

In [8]:
c = np.arange(10, 20)

print(c)
print('')

#np.linspace() -> Permite criar um array uniformemente espaçados seguindo os elementos passados como parametro.
d = np.linspace(1,3,10, endpoint=False) 
print(d)
print(' ')

e = np.logspace(0,5,10) # Permite criar um array uniformemente espaçados em escala logarítmica seguindo os elementos passados como parametro.
print(e)

[10 11 12 13 14 15 16 17 18 19]

[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8]
 
[1.00000000e+00 3.59381366e+00 1.29154967e+01 4.64158883e+01
 1.66810054e+02 5.99484250e+02 2.15443469e+03 7.74263683e+03
 2.78255940e+04 1.00000000e+05]


In [9]:
# Criando array com a função arrange
v2 = np.arange(10)

print(v2)
print('')

print(v2[1:9:2]) # Fatiamento usando [start: stop: step]
print('')

[0 1 2 3 4 5 6 7 8 9]

[1 3 5 7]



In [10]:
v = np.array([10, 33, 78, 100, 175])

print(np.mean(v)) # Calculando a média, aponta para onde se concentram os dados
print(' ')

print(np.std(v)) # Desvio padrão, variação existente em relação a média
print(' ')

print(np.var(v)) # Indica o quão longe os valores estão do esperado
print(' ')

print(np.sum(v)) # Somatória dos números da array
print(' ')

print(np.prod(v)) #Retona o produto(multiplicação) da matriz
print(' ')

79.2
 
57.50617358162513
 
3306.96
 
396
 
450450000
 


In [11]:
# Linha VS Coluna
print(np.shape(v))

(5,)


In [12]:
# Comparando vetores
v3 = np.array([2, 2, 3, 1])
v4 = np.array([4, 5, 3, 1])

print(v3==v4) # Analisa se os ítens das arrays são iguais
print(' ')

print(v3.min()) # Valor mínimo
print(v3.max()) # Valor máximo

[False False  True  True]
 
1
3


In [13]:
# Criando uma máscara boleana para elementos pares
mask = (v3 % 2 ==0)
print(mask)

[ True  True False False]


In [14]:
# Criando arrays com números repetidos a partir dos valores de outro vetor
v5 = np.repeat(v3, 3)
print(v5)
print(' ')

# Juntando dois vetores
v6 = np.concatenate((v3, v4), axis=0)
print(v6)

[2 2 2 2 2 2 3 3 3 1 1 1]
 
[2 2 3 1 4 5 3 1]


#### Manipulação de Matrizes

In [15]:
matr = np.array([[1,2,3],[4,5,6]])
print(matr)

[[1 2 3]
 [4 5 6]]


In [16]:
lista = [[1,2,3], [4,5,6], [7,8,9]]

In [17]:
# Criando matriz apartir de uma lista

m = np.matrix(lista)
print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
type(m)

numpy.matrix

In [19]:
# dtype
x= np.array([1,2]) # int
y= np.array([1.0,2.0]) # float
z= np.array([1,2], dtype=np.float64) # Forçamos um tipo de dado em particular

In [20]:
print(x.dtype, y.dtype, z.dtype)

int64 float64 float64


In [21]:
print(m.itemsize) # Tamanho em bytes de cada elemento
print(m.nbytes) # Bytes da matriz
print(m.ndim) # Número de dimensões

8
72
2


#### Manipulando Arquivos com Numpy

In [22]:
import os
import pandas as pd

In [29]:
arquivo = pd.read_csv("/home/karinag/karina_python/git-hub/numpy/dataset/dataset.csv")

In [30]:
arquivo.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [25]:
# Chamando o arquivo
filename = os.path.join("/home/karinag/karina_python/git-hub/numpy/dataset/dataset.csv")

In [27]:
# Carregando um dataset para dentro de uma array
arr1 = np.loadtxt(filename, delimiter=',', usecols=(0,1,2,3), skiprows=1)