<a href="https://colab.research.google.com/github/KARINAgoncalvesSOARES/numpy/blob/main/numpy_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy

Primeiro, é importante lembrar que você precisa importar essa biblioteca no seu código. Convencionou-se que a bibliteca deve ser importada da seguite maneira:



In [1]:
import numpy as np

Agora, vejamos um primeiro exemplo de criação de um array Numpy:

In [3]:
a = np.array([0,1,2,3])
print(a)
print(type(a))
print(a.ndim)

[0 1 2 3]
<class 'numpy.ndarray'>
1


###Criação de Arrays
####Construção Manual de Arrays


In [5]:
b = np.array([[0,1,2],
              [3,4,5]])

print(b)
print(b.ndim)
print(b.shape)
print(len(b))

[[0 1 2]
 [3 4 5]]
2
(2, 3)
2


####Criação utilizando funções

In [21]:
c = np.arange(10, 20)

print(c)
print('')

#np.linspace() -> Permite criar um array uniformemente espaçados seguindo os elementos passados como parametro.
d = np.linspace(1,10,13, endpoint=False) 
print(d)

[10 11 12 13 14 15 16 17 18 19]

[1.         1.69230769 2.38461538 3.07692308 3.76923077 4.46153846
 5.15384615 5.84615385 6.53846154 7.23076923 7.92307692 8.61538462
 9.30769231]


### Arrays comuns

In [22]:
#um = np.ones(3)
um = np.ones((2,3))
print(um)
print('')

#e = np.zeros(5)
e = np.zeros((5,5))
print(e)
print('')

f = np.random.rand(10,10) #Criando um array de números aleatórios
print(f)

[[1. 1. 1.]
 [1. 1. 1.]]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[0.96455023 0.91887268 0.21619094 0.95408054 0.38525438 0.0696711
  0.77587194 0.71590452 0.70248346 0.7617989 ]
 [0.35293041 0.39761371 0.40491033 0.07346459 0.66725055 0.31164855
  0.19734264 0.22667883 0.98592529 0.52200411]
 [0.38973671 0.98088681 0.19970065 0.06438248 0.85567658 0.45680277
  0.35601654 0.33271728 0.46242319 0.03897849]
 [0.95401411 0.56553178 0.56307999 0.06660565 0.20325566 0.39558651
  0.77909097 0.52226864 0.80608441 0.45620285]
 [0.56937847 0.81168338 0.06884311 0.85878242 0.79642808 0.60162717
  0.0018526  0.8506006  0.39277511 0.49951862]
 [0.64748641 0.65467687 0.03279549 0.36162363 0.01610011 0.61136005
  0.01353015 0.69828156 0.47364444 0.45694748]
 [0.65559581 0.60856815 0.85263426 0.17235958 0.6139532  0.23271996
  0.51199589 0.35288564 0.96144821 0.73326715]
 [0.71898614 0.75801066 0.23980445 0.00472412 0.36894185 0.72516502
  0.233578

In [25]:
# Criando array diagonal
g = np.eye(3)
print(g)
print('')

h = np.diag(np.array([1,2,3,4]))
print(h)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


###Indexação e Cortes (Slices) de Arrays

In [37]:
a = np.arange(10,21)
print(a)
print(a[-2]) # Acessando elementos da array
print('')

print(a[2:9])
print('')
print(a[8:2:-1])

[10 11 12 13 14 15 16 17 18 19 20]
19

[12 13 14 15 16 17 18]

[18 17 16 15 14 13]


In [35]:
b = np.random.rand(5,5)
print(b)
print('')
print(b[0][1]) # Culuna x linha
print('')

b[0,1] = 10 # Mudando o valor da array passando a posição como parâmetro
print(b)
print('')

# Slice
print(b[0:2, 2]) # Aqui está sendo específicado as linhas(0 e 2) e a coluna(2)

[[0.72786528 0.93579295 0.61717129 0.01559546 0.530037  ]
 [0.16791127 0.75077687 0.40702436 0.38301724 0.60701775]
 [0.25590353 0.82129093 0.29957353 0.75312203 0.78832782]
 [0.84087055 0.33126089 0.98968041 0.94881701 0.47261662]
 [0.08777909 0.68131331 0.64730918 0.34835878 0.65864375]]

0.9357929548046835

[[ 0.72786528 10.          0.61717129  0.01559546  0.530037  ]
 [ 0.16791127  0.75077687  0.40702436  0.38301724  0.60701775]
 [ 0.25590353  0.82129093  0.29957353  0.75312203  0.78832782]
 [ 0.84087055  0.33126089  0.98968041  0.94881701  0.47261662]
 [ 0.08777909  0.68131331  0.64730918  0.34835878  0.65864375]]

[0.61717129 0.40702436]
