<a href="https://colab.research.google.com/github/KARINAgoncalvesSOARES/numpy/blob/main/numpy_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 <h1 align="center"> Numpy</h1>

Data Scientist Jr.: Karina Gonçalves Soares

Link de estudo:

* [Bibliotecas para manipulação de dados](https://learn-us-east-1-prod-fleet02-xythos.content.blackboardcdn.com/5d152e0e8981d/17844897?X-Blackboard-S3-Bucket=learn-us-east-1-prod-fleet01-xythos&X-Blackboard-Expiration=1676505600000&X-Blackboard-Signature=lkHWJZohlEWpQ4r9xwnIjUZ3RGxIGMMciiSVvk%2Baohk%3D&X-Blackboard-Client-Id=152625&X-Blackboard-S3-Region=us-east-1&response-cache-control=private%2C%20max-age%3D21600&response-content-disposition=inline%3B%20filename%2A%3DUTF-8%27%27teorico.pdf&response-content-type=application%2Fpdf&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEJv%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMSJIMEYCIQCz%2BSTP0jHEwfxCWjOwiV1PgTzx7LZjL0Z5HWaEW8KEXQIhAPS%2Fau4SSdNNAv5HOuSIdsBwpqYR9zyJsbQoPrUqRUyeKs0ECDQQAhoMNjM1NTY3OTI0MTgzIgyBdytIECm3AKRatKIqqgTzix%2BevMIqCDspb%2BhXZTepfVS2xhAzm1%2FOfzI5LCpbftphP6tbTyGdlsi1InvwBWZpxPKkWyeDxL2QBZAbQ6mCj6fkeYEO4cQ5VSsdoXkSRZo6vuF3mZMrfENOAesTzPNGPif0eL0SmhPxVbjhW3KsR%2B7giCyXQslop0BUWArhlg6LP6lN%2BgoHXJtyGxD8ZAOMO68EAmxkq%2Fv3ccfrhHvsMb0T%2BKPPG82xEfcHMkRysUezj84pwJNF3jncEqkZG4aQMgywwx5qmEgaVaSi3CqYZ9FTpy0iZPJX4CaTJd5gcPJQHgvsnhOPnWpY4OfwO53B7hjom9gdsyJhwLgydgKdqm6rKOaUlnDuoyzyz%2BP4%2Bb3eUobA28k8ca412WEVAehBI2ThqudBReXJDEijQkaUx%2F%2BLawtPSNYsytAx9gow997HVvMTDA4%2FXkXXiynNh8ItpONH8FYUYeRdROl6cZUCAf9jikzGjio3OYcZ4IaZBOUV%2FzaENK4Qhh3TV9VGpk0HjQ5sa%2FRICNNTQdRqva8yAa%2FW1jmOpjERXEgzC%2BBLOOLP5CcXbxIhaFwLuAbzw4%2FWh8N91wRdfdmRGJjzFyang19yBkrIOMxjTMxhg8XScCaiylIwNO2jSxNg7DwttsFS5kqLeSZKXnzS2EaYzyBKj3LA46aYLMxP5vJjcuQbzxicy1o9beELRnZuUNiS1HsqlhQvNoqoTUIGPcoCGJjXamoMEui18QY%2FQDD90rSfBjqoAfvZtBSbpkDVbPq%2BYzcufEilTBDv231baoDQ%2BozCO00asGfef9t1FnayCeJTUYkCrcF%2FieTxnRKNLH6Vp7eY2upnDhUfcBY54ZGoiiOR41U6ZeHR%2BxPAB11HkSKfgyclg2wJrCK9E5Oxgd63v3SV%2FYjfn3yZzLnYTBZU1JZHc0DkuZoUgNxk8JaIpXgPEzJGxc1F34E0KEpPz0cWLUOAkLyjRnBN30bmrQ%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20230215T180000Z&X-Amz-SignedHeaders=host&X-Amz-Expires=21600&X-Amz-Credential=ASIAZH6WM4PL3WFKSPVS%2F20230215%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=c2e29328a6cdff83162514e353a47d7bc0ca38509d88decd0b5d1aa0950969b8)

#Numpy

Primeiro, é importante lembrar que você precisa importar essa biblioteca no seu código. Convencionou-se que a bibliteca deve ser importada da seguite maneira:



In [1]:
import numpy as np

Agora, vejamos um primeiro exemplo de criação de um array Numpy:

In [2]:
a = np.array([0,1,2,3])
print(a)
print(type(a))
print(a.ndim)

[0 1 2 3]
<class 'numpy.ndarray'>
1


### Criação de Arrays
#### Construção Manual de Arrays


In [3]:
b = np.array([[0,1,2],
              [3,4,5]])

print(b)
print('\n')
print(b.ndim)
print('\n')
print(b.shape)
print('\n')
print(len(b))
print('\n')
print(b.cumsum()) # Realiza a soma dos elementos do vetor

[[0 1 2]
 [3 4 5]]


2


(2, 3)


2


[ 0  1  3  6 10 15]


#### Criação utilizando funções

In [4]:
c = np.arange(10, 20)

print(c)
print('')

#np.linspace() -> Permite criar um array uniformemente espaçados seguindo os elementos passados como parametro.
d = np.linspace(1,10,13, endpoint=False) 
print(d)

[10 11 12 13 14 15 16 17 18 19]

[1.         1.69230769 2.38461538 3.07692308 3.76923077 4.46153846
 5.15384615 5.84615385 6.53846154 7.23076923 7.92307692 8.61538462
 9.30769231]


### Arrays comuns

In [5]:
#um = np.ones(3)
um = np.ones((2,3))
print(um)
print('')

#e = np.zeros(5)
e = np.zeros((5,5))
print(e)
print('')

f = np.random.rand(10,10) #Criando um array de números aleatórios
print(f)

[[1. 1. 1.]
 [1. 1. 1.]]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[0.55546107 0.93320934 0.69901199 0.14546225 0.63820777 0.45710514
  0.01341083 0.63153303 0.50444912 0.41787784]
 [0.10566977 0.61073691 0.48008795 0.90652572 0.0092639  0.74939474
  0.40647187 0.38245052 0.13822729 0.78248151]
 [0.8083691  0.20725447 0.47358131 0.35931833 0.71093247 0.61512583
  0.99705642 0.25244168 0.8222232  0.52098764]
 [0.7815797  0.12987947 0.83182849 0.46025671 0.05905265 0.465829
  0.40714261 0.25056232 0.92489161 0.82806643]
 [0.67880623 0.18787095 0.24670888 0.93467054 0.42710694 0.30740503
  0.37476309 0.41732234 0.80309215 0.3914338 ]
 [0.22698211 0.90569118 0.54750861 0.42010897 0.07348637 0.91610073
  0.43529598 0.79764381 0.2051447  0.70617994]
 [0.56713193 0.10000528 0.68301941 0.90331102 0.54231216 0.22056445
  0.58465003 0.85771743 0.18028037 0.22200621]
 [0.69157898 0.16418928 0.18598868 0.07569489 0.53821326 0.56199676
  0.4015926

In [6]:
# Criando array diagonal
g = np.eye(3)
print(g)
print('')

h = np.diag(np.array([1,2,3,4]))
print(h)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


###Indexação e Cortes (Slices) de Arrays

In [7]:
a = np.arange(10,21)
print(a)
print(a[-2]) # Acessando elementos da array
print('')

print(a[2:9])
print('')
print(a[8:2:-1])

[10 11 12 13 14 15 16 17 18 19 20]
19

[12 13 14 15 16 17 18]

[18 17 16 15 14 13]


In [8]:
b = np.random.rand(5,5)
print(b)
print('')
print(b[0][1]) # Culuna x linha
print('')

b[0,1] = 10 # Mudando o valor da array passando a posição como parâmetro
print(b)
print('')

# Slice
print(b[0:2, 2]) # Aqui está sendo específicado as linhas(0 e 2) e a coluna(2)
print(' ')
print(b.size) # Saber quantidade de elementos

[[0.71490121 0.89298021 0.2370173  0.39747223 0.23710753]
 [0.55595663 0.77245852 0.26482328 0.30410392 0.49865511]
 [0.05537228 0.98691012 0.05036    0.55868572 0.74116102]
 [0.98921443 0.74813652 0.60575486 0.50541752 0.50896588]
 [0.9897879  0.42178027 0.52860049 0.48140522 0.02624455]]

0.892980208184989

[[ 0.71490121 10.          0.2370173   0.39747223  0.23710753]
 [ 0.55595663  0.77245852  0.26482328  0.30410392  0.49865511]
 [ 0.05537228  0.98691012  0.05036     0.55868572  0.74116102]
 [ 0.98921443  0.74813652  0.60575486  0.50541752  0.50896588]
 [ 0.9897879   0.42178027  0.52860049  0.48140522  0.02624455]]

[0.2370173  0.26482328]
 
25


In [9]:
v = np.array([10, 33, 78, 100, 175])

print(np.mean(v)) # Calculando a média, aponta para onde se concentram os dados
print(' ')

print(np.std(v)) # Desvio padrão, variação existente em relação a média
print(' ')

print(np.var(v)) # Indica o quão longe os valores estão do esperado
print(' ')

print(np.sum(v)) # Somatória dos números da array
print(' ')

print(np.prod(v)) #Retona o produto(multiplicação) da matriz
print(' ')

79.2
 
57.50617358162513
 
3306.96
 
396
 
450450000
 


In [10]:
v2 = np.arange(10)

print(v2)
print('')

print(v2[1:9:2]) # Fatiamento usando [start: stop: step]
print('')

[0 1 2 3 4 5 6 7 8 9]

[1 3 5 7]



In [11]:
# Comparando vetores
v3 = np.array([2, 2, 3, 1])
v4 = np.array([4, 5, 3, 1])

print(v3==v4) # Analisa se os ítens das arrays são iguais
print(' ')

print(v3.min()) # Valor mínimo
print(v3.max()) # Valor máximo

[False False  True  True]
 
1
3


In [12]:
# Criando arrays com números repetidos a partir dos valores de outro vetor
v5 = np.repeat(v3, 3)
print(v5)
print(' ')

# Juntando dois vetores
v6 = np.concatenate((v3, v4), axis=0)
print(v6)

[2 2 2 2 2 2 3 3 3 1 1 1]
 
[2 2 3 1 4 5 3 1]
